name: Commit Actions
on:
  pull_request:
    types: [synchronize]
jobs:
  remove-labels:
    uses: daniel-test-bed/workflows/.github/workflows/remove-labels.yml@main
    with:
      labels: ok-to-test
