name: CI
on:
  issue_comment:
    types:
      - created
jobs:
  mustpass:
    # This job only runs for pull request comments
    name: Job Must Pass
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/run pipeline' && github.event.comment.author_association=='CONTRIBUTOR' }}
    uses: daniel-test-bed/workflows/.github/workflows/wf-wrapper.yml@main
    with:
      status-name: "CI/Job Must Pass"
      name: ${{ github.event.comment.user.login }}
      
  notify_contributor_and_label_required:
    uses: daniel-test-bed/workflows/.github/workflows/post-usage.yml@main
