name: CI
on:
  issue_comment:
    types:
      - created
jobs:
  mustpass:
    # This job only runs for pull request comments
    name: Job Must Pass
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/run pipeline' && github.event.comment.author_association=='CONTRIBUTOR' }}
    uses: daniel-test-bed/workflows/.github/workflows/wf-wrapper.yml@main
    with:
      status-name: "CI/Job Must Pass"
      name: ${{ github.event.comment.user.login }}
      
  notify_contributor_and_label_required:
    name: Notify Contributor and Label Required
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/run pipeline' && (github.event.comment.author_association != 'CONTRIBUTOR' || !contains(github.event.issue.labels.*.name, 'ok-to-test')) }}
    steps:
      - name: Post Comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            You must be a contributor and the pull request needs the `ok-to-test` label in order to trigger the pipeline.
