name: CI
on:
  issue_comment:
    types:
     - created
     - edited
jobs:    
  mustpass:
      # This job only runs for pull request comments
      name: Job Must Pass
      if: ${{ github.event.issue.pull_request && github.event.comment.body == '/run pipeline' }}
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            ref: ${{ github.event.pull_request.head.sha }}
            
        - run: echo "${{ github.event.comment.body }}"

