on:
  issue_comment:
    types:
     - created
     - edited
jobs:
  pr_commented:
      # This job only runs for pull request comments
      name: PR comment
      if: ${{ github.event.issue.pull_request }}
      runs-on: ubuntu-latest
      steps:
        - run: |
            echo "A comment Message: ${{ github.comment.body }}"

