name: CI
on:
  issue_comment:
    types:
      - created
jobs:
  # If issue comment equals Ready for review add the label ready-for-review to the pr
  add-review-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add label
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            const issueNumber = context.issue.number;
            const repo = context.repo;
            const commentBody = context.payload.comment.body.trim().toLowerCase();
            if (commentBody === 'ready for review') {
              github.issues.addLabels({
                ...repo,
                issue_number: issueNumber,
                labels: ['ready-for-review']
              });
            }
  mustpass:
    # This job only runs for pull request comments
    name: Job Must Pass
    uses: daniel-test-bed/workflows/.github/workflows/wf-wrapper.yml@main
    secrets: inherit
    with:
      status-name: "CI/Job Must Pass"
      name: ${{ github.event.comment.user.login }}
