on:
  issue_comment:
    types:
     - created
     - edited
env:
   PIPELINE_TRIGGER: ${{ vars.PIPELINE_TRIGGER }}
jobs:
  first:
    name: debug
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ env.PIPELINE_TRIGGER }}"
    
  mustpass:
      # This job only runs for pull request comments
      name: Job Must Pass
      if: ${{ github.event.comment.body == env.PIPELINE_TRIGGER }}
      runs-on: ubuntu-latest
      steps:
        - run: echo "${{ github.event.comment.body }}"
        - name: Add commit status
          uses: actions/github-script@v4
          with:
            script: |
              const github = require('@actions/github');
              const octokit = new github.GitHub(process.env.GITHUB_TOKEN);
              const context = github.context;

              octokit.repos.createCommitStatus({
                owner: context.repo.owner,
                repo: context.repo.repo,
                sha: context.sha,
                state: 'success',
                target_url: '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}',
                description: 'Must Pass'
              });
